### PR TITLE
Avoid uninteresting user facing errors

### LINKED ISSUE #695: Test discovery throws error when a workspace folder path is invalid
**Describe the bug**
QL test discovery throws a user-facing error if one of the workspace folder entries in a multi-root workspace does not exist on the filesystem.

**To Reproduce**
1. Create a VS Code `.code-workspace` file (or update an existing one) with the following entry:
    ```
    {
      "folders": [
        {
          "path": "/does/not/exist"
        }
    }
    ```
1. Open that workspace file in VS Code with the CodeQL extension active.
1. Activate the CodeQL extension, e.g. by clicking on the CodeQL sidebar panel. (Not necessary if the workspace has CodeQL-related source files or databases that would activate the extension.)
1. The extension throws an error:
```
QL Test Discovery failed. Reason: Resolving tests failed: A fatal error occurred: /does/not/exist does not exist.
[2020-11-30 14:30:07] Exception caught at top level: /does/not/exist does not exist.
                      com.semmle.cli2.resolve.ResolveTestsCommand.executeJSON(ResolveTestsCommand.java:79)
                      com.semmle.cli2.resolve.ResolveTestsCommand.executeJSON(ResolveTestsCommand.java:33)
                      com.semmle.cli2.picocli.SimpleJsonSubcommand.executeInsistingOnJSON(SimpleJsonSubcommand.java:101)
                      com.semmle.cli2.picocli.SimpleJsonSubcommand.executeSubcommand(SimpleJsonSubcommand.java:77)
                      com.semmle.cli2.picocli.SubcommandCommon.executeWithParent(SubcommandCommon.java:414)
                      com.semmle.cli2.execute.CliServerCommand.lambda$executeSubcommand$0(CliServerCommand.java:67)
                      com.semmle.cli2.picocli.SubcommandMaker.runMain(SubcommandMaker.java:201)
                      com.semmle.cli2.execute.CliServerCommand.executeSubcommand(CliServerCommand.java:67)
                      com.semmle.cli2.picocli.SubcommandCommon.call(SubcommandCommon.java:430)
                      com.semmle.cli2.picocli.SubcommandMaker.runMain(SubcommandMaker.java:201)
                      com.semmle.cli2.picocli.SubcommandMaker.runMain(SubcommandMaker.java:209)
                      com.semmle.cli2.CodeQL.main(CodeQL.java:91)
```

**Expected behavior**
Test discovery fails gracefully on non-existent workspace folders, and logs a warning without alerting the user.

**Additional context**
I ran into this for somewhat arcane reasons: I had migrated data between machines, and the filesystem paths to my home directory were different, making the absolute paths in the workspace file incorrect.
A user is more likely to run into this if they delete a directory (source or CodeQL database) from their filesystem without also removing it from the workspace.

### PR DESCRIPTION
**Pull request by aeisenberg**
This change avoids popping up error messages in two cases:

1. When doing test discovery, do not run discovery on non-existant
   directories. Also, if there is an error, print to the log, and do not
   pop up an error window. The reason is that test discovery is a
   background operation and these should not normally cause pop-ups.
2. When looking for orphaned databases, don't pop up an error if the
   storagePath can't be found. This is normal when working in a new,
   single root workspace.

Fixes #695

## Checklist

- [x] [CHANGELOG.md](https://github.com/github/vscode-codeql/blob/main/extensions/ql-vscode/CHANGELOG.md) has been updated to incorporate all user visible changes made by this pull request.
- [x] Issues have been created for any UI or other user-facing changes made by this pull request.
- [n/a] `@github/docs-content-dsp` has been cc'd in all issues for UI or other user-facing changes made by this pull request.

### CODE REVIEW

File: extensions/ql-vscode/src/databases-ui.ts [hunk 1]
```diff
@@ -378,21 +378,28 @@ export class DatabaseUI extends DisposableObject {
...
+          // remove databases still in workspace
+          .filter(dbDir => {
+            const dbUri = Uri.file(dbDir);
+            return this.databaseManager.databaseItems.every(item => item.databaseUri.fsPath !== dbUri.fsPath);
+          });
+
+      // remove non-databases
+      dbDirs = await asyncFilter(dbDirs, isLikelyDatabaseRoot);
+    } catch (e) {
+      logger.log(`Not able to find the storage path '${e.message}'. Ignoring request to remove orphaned database directories.`);
```
Comment (adityasharad) [inline extensions/ql-vscode/src/databases-ui.ts:400]: Minor: You could do a check up front with `await fs.exists(this.storagePath)` so that we can distinguish between the storage path not existing, and some other failure to read its contents.
```suggestion
      logger.log(`Not able to read from the storage path '${e.message}'. Ignoring request to remove orphaned database directories.`);
```

**Review by adityasharad — APPROVED** [review]
Nice!

File: extensions/ql-vscode/src/databases-ui.ts (hunk 1 above)
Comment (aeisenberg) [reply extensions/ql-vscode/src/databases-ui.ts:400]: Let me do that and fix it up a bit more.

Comment (aeisenberg) [reply extensions/ql-vscode/src/databases-ui.ts]: OK. I removed the try/catch around collecting the `dbDirs` since if there is an error at this point, that indicates something much stranger going on that might actually be important for the user.

File: extensions/ql-vscode/src/databases-ui.ts [hunk 2]
```diff
@@ -378,7 +378,17 @@ export class DatabaseUI extends DisposableObject {
...
   handleRemoveOrphanedDatabases = async (): Promise<void> => {
     logger.log('Removing orphaned databases from workspace storage.');
-    let dbDirs =
+    let dbDirs = undefined;
+
+    if (
+      !(await fs.pathExists(this.storagePath) ||
+        !(await fs.stat(this.storagePath)).isDirectory())
+    ) {
+      // ignore a missing or invalid storage directory.
```
Comment (adityasharad) [inline extensions/ql-vscode/src/databases-ui.ts:387]: You had a log message for this before, I suggest keeping that.

Comment (aeisenberg) [reply extensions/ql-vscode/src/databases-ui.ts:387]: Sure.

**Review by adityasharad — APPROVED** [review]
