### PR TITLE
fix: Use a proper 'file' schema for uris

### LINKED ISSUE #314: Bug: Error when trying to open query log file (on Windows)
### Describe the bug

The right-click query history option **Show Query Log** doesn't work for me. I get the following error:

```
Could not open log file c:\Users\Shati Patel\AppData\Roaming\Code\User\workspaceStorage\f69b706cc42093b6075931e719082fad\GitHub.vscode-codeql\CodeQL Query Server\query-test.ql-1.log
cannot open c:%5CUsers%5CShati%20Patel%5CAppData%5CRoaming%5CCode%5CUser%5CworkspaceStorage%5Cf69b706cc42093b6075931e719082fad%5CGitHub.vscode-codeql%5CCodeQL%20Query%20Server%5Cquery-test.ql-1.log. Detail: resource is not available
Error: cannot open c:%5CUsers%5CShati%20Patel%5CAppData%5CRoaming%5CCode%5CUser%5CworkspaceStorage%5Cf69b706cc42093b6075931e719082fad%5CGitHub.vscode-codeql%5CCodeQL%20Query%20Server%5Cquery-test.ql-1.log. Detail: resource is not available
    at file:///C:/Users/Shati Patel/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4156:737
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

### Additional context
Running v.1.1.1 of the extension on Windows.

### PR DESCRIPTION
**Pull request by aeisenberg**
Closes #314 .

### CODE REVIEW

File: extensions/ql-vscode/src/query-history.ts [hunk 1]
```diff
@@ -192,7 +192,7 @@ export class QueryHistoryManager {
 
   async handleShowQueryLog(queryHistoryItem: CompletedQuery) {
     if (queryHistoryItem.logFileLocation) {
-      const uri = vscode.Uri.parse(queryHistoryItem.logFileLocation);
+      const uri = vscode.Uri.parse('file:' + queryHistoryItem.logFileLocation);
```
Comment (adityasharad) [inline extensions/ql-vscode/src/query-history.ts]: Does this work when your log file path contains `#`? (cf the example for the `file` method at https://code.visualstudio.com/api/references/vscode-api#Uri)
If `logFileLocation` is a filesystem path then I think we should be using `vscode.Uri.file`.
If it's a URI then what happens if it already has a scheme?

Comment (aeisenberg) [reply extensions/ql-vscode/src/query-history.ts]: `logFileLocation` is a string. I think the `uri.file` method is the one to use. Thanks for catching that.
