### PR TITLE
Ensure `--addtional-packs` arg not used for empty workspace

### LINKED ISSUE #1066: Resolving upgrades takes a long time when the current workspace has no workspace roots
**Describe the bug**

Resolving upgrades will scan the user's home directory for upgrades if the current workspace has no open folders. Normally, all workspace folders are concatenated and passed to the `--additional-packs` argument. However, when there are no folders, the value is an empty string, which corresponds to the CWD of the vscode process (typically, the user's home directory).

**To reproduce**

1. Open an empty workspace
2. Add a database
3. Remove that database's source folder
4. Open a quick query editor tab
5. run a simple query like `select 1`
6. BUG: `resolve upgrades` stage takes a long time

The proper solution is to avoid using an `--additional-packs` argument if there are no workspace folders. Also, we should verify that only `file:` based folders are included. Remote folders and archive folders should be excluded as well. This may already be happening, but we should verify this.

### PR DESCRIPTION
**Pull request by aeisenberg**
Fixes #1066

## Checklist

- [x] [CHANGELOG.md](https://github.com/github/vscode-codeql/blob/main/extensions/ql-vscode/CHANGELOG.md) has been updated to incorporate all user visible changes made by this pull request.
- [x] Issues have been created for any UI or other user-facing changes made by this pull request.
- [x] _[Maintainers only]_ If this pull request makes user-facing changes that require documentation changes, open a corresponding docs pull request in the [github/codeql](https://github.com/github/codeql/tree/main/docs/codeql/codeql-for-visual-studio-code) repo and add the `ready-for-doc-review` label there.

### CODE REVIEW

File: extensions/ql-vscode/src/cli.ts [hunk 1]
```diff
@@ -929,6 +930,12 @@ export class CodeQLCliServer implements Disposable {
         throw new Error('No distribution found');
     }
   }
+
+  private getAdditionalPacksArg(paths: string[]): string[] {
```
Comment (henrymercer) [inline extensions/ql-vscode/src/cli.ts:934]: Minor: Is `Args` more appropriate here since the return type is an array?

**Review by henrymercer — APPROVED** [review]

File: extensions/ql-vscode/src/cli.ts (hunk 1 above)
Comment (aeisenberg) [reply extensions/ql-vscode/src/cli.ts:934]: I used `Arg` (singular) since this method returns the `--additional-packs` argument.
