### PR TITLE
Fix set label command on history items

### LINKED ISSUE #709: Set Label on a query history item is broken
The "Set label" command does not affect the UI. The problem is that the tree items are being cached and even though we are updating the label on the query item, the tree item is not reflecting this change.

This bug was introduced in #598. I have a different way to address #598 that will also fix the label.

### PR DESCRIPTION
**Pull request by aeisenberg**
This removes the cached treeItem that is a property of the
completedQuery. We should not be caching them since they are cached by
the vscode api itself. Instead, we should recreate whenever requested.

Also, this change fixes #598 in a new way. Instead of adding the
context to the cached treeItem, we simply refresh only the item that has
changed. This is a fast operation.

Fixes #709.

## Checklist

- [x] [CHANGELOG.md](https://github.com/github/vscode-codeql/blob/main/extensions/ql-vscode/CHANGELOG.md) has been updated to incorporate all user visible changes made by this pull request.
- [x] Issues have been created for any UI or other user-facing changes made by this pull request.
- [n/a] `@github/docs-content-dsp` has been cc'd in all issues for UI or other user-facing changes made by this pull request.

### CODE REVIEW

**Comment by aeisenberg** [comment]
Converting to draft since I want to add a few unit tests.

File: extensions/ql-vscode/src/query-history.ts [hunk 1]
```diff
@@ -157,8 +144,8 @@ class HistoryTreeDataProvider extends DisposableObject implements QueryHistoryDa
     return this.history;
   }
 
-  refresh() {
-    this._onDidChangeTreeData.fire(undefined);
+  refresh(CompletedQuery?: CompletedQuery) {
```
Comment (adityasharad) [inline extensions/ql-vscode/src/query-history.ts:147]: Lowercase the variable to distinguish them.

**Review by adityasharad — COMMENTED** [review]
Looks very reasonable. I'll wait for tests :)

**Review by adityasharad — APPROVED** [review]
