### PR TITLE
Avoid opening the results panel on db deletion

### LINKED ISSUE #823: Removing database reopens "CodeQL Query Results" panel
**Version**
Extension version 1.4.5

**Describe the bug**
It looks like removing a database always reopens the "CodeQL Query Results" panel.
It does not seem to matter whether:
- There is more than one database, and the other ones are not removed
- The removed database was the "current" one
- The removed database was loaded from a folder or from a .zip file
- Another panel is already open
- The query history is empty

**To Reproduce**
1. Load a database
2. Close the "CodeQL Query Results" panel (in case it is open)
3. Remove the database
:x: The "CodeQL Query Results" panel is opened

**Expected behavior**
The "CodeQL Query Results" panel is not opened.

### PR DESCRIPTION
**Pull request by aeisenberg**
Fixes #823

Replace this with a description of the changes your pull request makes.

## Checklist

- [x] [CHANGELOG.md](https://github.com/github/vscode-codeql/blob/main/extensions/ql-vscode/CHANGELOG.md) has been updated to incorporate all user visible changes made by this pull request.
- [x] Issues have been created for any UI or other user-facing changes made by this pull request.
- [n/a] `@github/docs-content-codeql` has been cc'd in all issues for UI or other user-facing changes made by this pull request.

### CODE REVIEW

File: extensions/ql-vscode/src/interface.ts [hunk 1]
```diff
@@ -168,6 +174,14 @@ export class InterfaceManager extends DisposableObject {
...
         }
       ));
+      // this._panel.onDidChangeViewState(
+      //   (e) => {
+      //     this.logger.log(JSON.stringify(e));
+      //   },
+      //   null,
+      //   ctx.subscriptions
+      // );
+
```
Comment (henrymercer) [inline extensions/ql-vscode/src/interface.ts:184]: Did you intend to check this in?

**Review by henrymercer — APPROVED** [review]
Looks sensible.

File: extensions/ql-vscode/src/interface.ts (hunk 1 above)
Comment (aeisenberg) [reply extensions/ql-vscode/src/interface.ts:184]: Oops. No. Should be removed.
