### PR TITLE
fix: Avoid auto-updating the codeql binaries

### LINKED ISSUE #283: Updating CodeQL CLI hangs loading the workspace tree
**Describe the bug**
When I load VS Code, and there's an update to the CodeQL CLI available, the CLI is automatically downloaded. However, VS Code will not load my workspace tree whilst the CLI is downloading (it's simply blank).

It seems like we're doing the CLI update in some sort of initialization handler which is preventing the workspace tree from loading.

**To Reproduce**
Open VS Code after CodeQL CLI has been updated.

**Expected behavior**
Workspace tree should be available while new CodeQL CLI is downloading.

### PR DESCRIPTION
**Pull request by aeisenberg**
On startup, if a new binary is available, request user acceptance
before starting the update.

Fixes #283

### CODE REVIEW

**Comment by aeisenberg** [comment]
Good point. I haven't tried this on a newly installed instance. I'll make sure that if no binaries are available, then the download happens without user interaction.

File: extensions/ql-vscode/src/extension.ts [hunk 1]
```diff
@@ -216,16 +226,22 @@ export async function activate(ctx: ExtensionContext): Promise<void> {
 
   ctx.subscriptions.push(distributionConfigListener.onDidChangeDistributionConfiguration(() => installOrUpdateThenTryActivate({
     isUserInitiated: true,
-    shouldDisplayMessageWhenNoUpdates: false
+    shouldDisplayMessageWhenNoUpdates: false,
+
+    // only auto update on startup if the user has previously requested an update
+    // otherwise, ask user to accept the update
+    avoidAutoUpdating: !!ctx.globalState.get(shouldUpdateOnNextActivationKey)
```
Comment (henrymercer) [inline extensions/ql-vscode/src/extension.ts]: This call to `installOrUpdateThenTryActivate` happens when a user changes the distribution configuration, for example by changing the CodeQL executable path setting.  I think this logic for `shouldUpdateOnNextActivationKey` belongs in the final call to `installOrUpdateThenTryActivate` on lines 241 to 245.

File: extensions/ql-vscode/CHANGELOG.md [hunk 2]
```diff
@@ -4,6 +4,7 @@
 
 - Add new command in query history view to view the log file of a
   query.
+- Avoid updating the CodeQL binaries without user acknowledgment.
```
Comment (henrymercer) [inline extensions/ql-vscode/CHANGELOG.md]:
```suggestion
- Request user acknowledgment before updating the CodeQL binaries. 
```

Comment (aeisenberg) [reply extensions/ql-vscode/CHANGELOG.md]: Yep.

File: extensions/ql-vscode/src/extension.ts (hunk 1 above)
Comment (aeisenberg) [reply extensions/ql-vscode/src/extension.ts]: Darn. I messed that up. Fixed now. And a bit of refactoring/renaming that I hope makes things clearer.

File: extensions/ql-vscode/src/extension.ts [hunk 3]
```diff
@@ -112,7 +117,7 @@ export async function activate(ctx: ExtensionContext): Promise<void> {
         await noUpdatesLoggingFunc("CodeQL CLI is installed externally so could not be updated.");
         break;
       case DistributionUpdateCheckResultKind.UpdateAvailable:
-        if (beganMainExtensionActivation) {
+        if (beganMainExtensionActivation || !allowAutoUpdating) {
           const updateAvailableMessage = `Version "${result.updatedRelease.name}" of the CodeQL CLI is now available. ` +
             "The update will be installed after Visual Studio Code restarts. Restart now to upgrade?";
```
Comment (henrymercer) [inline extensions/ql-vscode/src/extension.ts]: This messaging is no longer correct:

```suggestion
            "Do you wish to upgrade?";
```

File: extensions/ql-vscode/src/extension.ts [hunk 4]
```diff
@@ -216,16 +226,22 @@ export async function activate(ctx: ExtensionContext): Promise<void> {
...
+    shouldDisplayMessageWhenNoUpdates: false,
+    allowAutoUpdating: true
   })));
   ctx.subscriptions.push(commands.registerCommand(checkForUpdatesCommand, () => installOrUpdateThenTryActivate({
     isUserInitiated: true,
-    shouldDisplayMessageWhenNoUpdates: true
+    shouldDisplayMessageWhenNoUpdates: true,
+
+    // only auto update on startup if the user has previously requested an update
+    // otherwise, ask user to accept the update
```
Comment (henrymercer) [inline extensions/ql-vscode/src/extension.ts]: I think you forgot to move the comment :)

**Comment by aeisenberg** [comment]
Also closes https://github.com/github/codeql-coreql-team/issues/193

**Comment by shati-patel** [comment]
Thanks for the ping, @henrymercer! I've raised an [issue](https://github.com/github/product-documentation/issues/2308) to change a line in the docs that mentions auto-updating. 

(It's a very minor change that won't cause any confusion in the meantime, so feel free to merge this PR whenever it suits 😃 )
