### PR TITLE
Fix paths on windows when opening archive databases

### LINKED ISSUE #373: Cannot open a local archive database on windows
Using the new `Choose database from archive` command on a windows machine, the database fails to open due to a path error.

Discovered by @shati-patel

### PR DESCRIPTION
**Pull request by aeisenberg**
Fixes #373.

### CODE REVIEW

File: extensions/ql-vscode/src/databaseFetcher.ts [hunk 1]
```diff
@@ -115,14 +115,17 @@ async function databaseArchiveFetcher(
 }
 
 async function getStorageFolder(storagePath: string, urlStr: string) {
+  // we need some approximation for a folder name
   const url = Uri.parse(urlStr);
-  let lastName = path.basename(url.path).substring(0, 255);
+  let lastName = path.basename(url.path).substring(0, 250);
```
Comment (jcreedcmu) [inline extensions/ql-vscode/src/databaseFetcher.ts:120]: What's going on with this length limit? Add a comment maybe?

File: extensions/ql-vscode/src/databaseFetcher.ts [hunk 2]
```diff
@@ -115,14 +115,17 @@ async function databaseArchiveFetcher(
 }
 
 async function getStorageFolder(storagePath: string, urlStr: string) {
+  // we need some approximation for a folder name
```
Comment (jcreedcmu) [inline extensions/ql-vscode/src/databaseFetcher.ts:118]: Not clear to me what's being approximated?

Comment (aeisenberg) [reply extensions/ql-vscode/src/databaseFetcher.ts:118]: I'll make that clearer. The max file name length is 260 on windows and 255 on macs. But the zip files tend to have very long names. Also, we add a few extra chars at the end in case there are duplicates.

I'm partially thinking that we should just avoid this and use a random name.

Comment (aeisenberg) [reply extensions/ql-vscode/src/databaseFetcher.ts:118]: Wait...we can't just use a random name since we also use the folder name as the database name when we import the database.
